Linear Rgression

In [108]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize

In [25]:
#read data
df = pd.read_table('ex1/ex1data2.txt',sep= ',',header=None)

In [110]:
df.columns = ['X1', 'X2','y']
df.head()

X1  X2       y
0  2104   3  399900
1  1600   3  329900
2  2400   3  369000
3  1416   2  232000
4  3000   4  539900

In [173]:
y=np.array([df.y])
m=len(y[0])
#df.X1= normalize(df.X1) ; df.X2=normalize(df.X2)
X=np.array((np.ones(m),df.X1,df.X2))
theta= np.array([np.zeros(len(X))])

In [174]:
X[1:3,:]=normalize(X[1:3,:]) #standardize X

In [175]:
print(theta.shape)
print(X.shape)

(1, 3)
(3, 47)


Cost function

In [147]:
def J(X,y,theta): 
    temp=(1/(2*m))*np.sum((theta.dot(X)-y)**2)
    return temp

In [125]:
J(X,y,theta)

2723198301766.223

Gradient Descent

In [176]:
#alpha = 0.01 ; num_iters = 400;
def GD(X,y,theta,alpha = 0.01 , num_iters = 400) :
    i=1
    while i <= num_iters :
        prediction = theta.dot(X)-y
        theta = theta - alpha*(1/m)*(prediction.dot(X.T))
        cost = J(X,y,theta)
        #print(cost)
        i+=1
    return theta, cost

In [177]:
result=GD(X,y,theta)

In [178]:
result[0]

array([[319810.24800963,  65320.44430557,  52405.20253127]])

In [182]:
X

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.14276982, 0.10857021, 0.16285531, 0.09608463, 0.20356914,
        0.13469491, 0.10409169, 0.09683105, 0.0936418 , 0.10137743,
        0.13164137, 0.13571276, 0.12824856, 0.30386086, 0.08604189,
        0.15606967, 0.08957042, 0.08387048, 0.17703729, 0.20567268,
        0.11990222, 0.12811284, 0.10884163, 0.13313422, 0.26396131,
        0.07464

In [181]:
result[0].dot(X)-y

array([[ -63726.02667587,    4040.03928281,  -31514.03366747,
          98778.49700346, -197408.60932227,   38092.4957334 ,
          18747.50030121,  134174.23255831,  120964.90934414,
          90970.20394872,   97794.03733685,  -11286.99719233,
           5226.43783833, -348511.53004   ,   72568.47955718,
        -110511.29549077,   30452.9857575 ,  132426.64247519,
        -159239.68116782, -256371.20464909,   81780.25155444,
          77870.5939628 ,   91057.76891806,   77990.55033072,
        -229809.74453737,   81823.83487674, -131189.36276851,
        -130955.55015714, -138400.5154299 ,   38636.44722101,
         -17246.594069  ,  156688.63587969,   23336.27821807,
        -239147.34837292,   51321.25660009,   83317.55664643,
         102439.93970162,   -6355.94017121, -201123.23261551,
          51777.03209315,  -36622.26561113,    6867.91610496,
          26572.15766207,   33167.07575795,  148378.61843341,
          37502.98536139,   92680.37298439]])